Django/learning_cbv/basic_app/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    # pk for primary key is an attribute of DetailView
    # SchoolDetailView will receive a pk and return detail view of instance with that id
    re_path(r"^(?P<pk>[\d]+)$", views.SchoolDetailView.as_view(), name='detail'),
    path('student/', views.studentFormView.as_view(), name='student'),
    re_path(r"^create/$", views.SchoolCreateView.as_view(), name='create'),
    re_path(r'^update/(?P<pk>[\d]+)$', views.SchoolUpdateView.as_view(), name='update'),
    re_path(r'^delete/(?P<pk>[\d]+)$', views.SchoolDeleteView.as_view(), name='delete'),
]

Django/learning_cbv/learning_cbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    # path('', views.index, name='index'),
    # path('', views.CBView.as_view(), name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('basic_app/', include('basic_app.urls', namespace='basic_app')),
    path('admin/', admin.site.urls),
]

Django/learning_cbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    """A Model representing a School"""

    name = models.CharField(max_length=100)
    principal = models.CharField(max_length=100)
    location = models.CharField(max_length=250)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """A URL to a page that represents this model."""

        # Creating reverse URL with view
        return reverse("basic_app:detail", kwargs={'pk':self.pk})


class Student(models.Model):
    """A model representing a student."""

    name = models.CharField(max_length=100)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='students', null=True)

    def __str__(self):
        return self.name

Django/learning_cbv/basic_app/forms.py
from django.forms import forms, ModelForm
from . import models

class StudentForm(ModelForm):

    class Meta:
        model = models.Student
        fields = "__all__"

Django/learning_cbv/basic_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import (View, TemplateView, ListView, 
                                    DetailView, CreateView, UpdateView,
                                    DeleteView, FormView)

from . import models
from . import forms

#____________Function based view______________#
def index(request):
    return render(request, 'index.html')

#_______________class based view_________________#
class CBView(View):
    """A basic CBV that is based on the Base generic View"""

    def get(self, request):

        return HttpResponse("Class Based views are awsome!")

#___________TemplateViews________________#
"""TemplateViews are used to render a template. If you want to make a view that does
multiple operations you can use, multiple abstract inheritance."""

class IndexView(TemplateView):

    template_name = 'index.html'
    #template_engine = The Name of the template engine to use for 
    #                   loading the template (Django template Engine default).
    #response_class = Custom template loading or custom context object instantiation.
    #content_type = Default Django uses 'text/html'

    def get_context_data(self, **kwargs):
        """Function for passing context dictionary to Template. """

        # Overriding getter method in super class.
        # assigning get method to 'context' identifier.
        context = super().get_context_data(**kwargs)
        # Adding key-value pair to context dictionary
        context['inject'] = 'Basic Injection'

        return context

#__________________________ListView_________________________________#
"""List views are used to display a list of Model objects. e.g. A feed of blog post
summaries, writen by a user."""

class SchoolListView(ListView):
    """By default the class will return a list named school_list"""

    # This changes default behaviour 
    context_object_name = 'schools'
    model = models.School

    """We can provide a template path to the this view but the view expects a
    template path similar to 'app_name/model_name_list.html' (all lower-case).
    It can be overriden by passing a path to template_name attribute of 
    TemplateResponseMixin class, a super class of ListView defined in base.py
    in django.views.generic """
    # template_name = 'basic_app/school_list.html'

#_________________________DetailView__________________________#
"""A detail view is used to display details of a specific instance of a Model.
It takes an argument pk for primary key of the instance to be detailed.
e.g. A view to display entire blog when a user clicks on a summary blog on his feed."""

class SchoolDetailView(DetailView):

    context_object_name = 'school_detail'
    model = models.School

    """Similar to ListView, DetailView expects a template path app/model_detail.html
    which can be overridden using template_name attribute."""
    template_name = 'basic_app/school_detail.html'


#________________________FormView__________________________________#
"""A FormView is used to render a form, It takes a Form/ModelForm instance, template_name
and a success_url to redirect to after submission."""
class studentFormView(FormView):

    form_class = forms.StudentForm
    template_name = 'basic_app/student_form.html'
    success_url = reverse_lazy('basic_app:list')

    def form_valid(self, form):
        """A superclass method to check form validation"""
        form.save()
        return super().form_valid(form)

#____________________________CRUD views_________________________________#
"""Create & Update views require a form template. By default they
will look for school_form (model_name_form.html [model name lower cased])
in local template directory."""

# CreateView___________________________#
"""Create view is used to create an instance of a Model.
e.g. Creating a Blog, User, group, etc."""
class SchoolCreateView(CreateView):

    # Model to create an instance of.
    model = models.School
    # Fields requeired to create an instance of this Model.
    fields = ('name', 'principal', 'location')

# UpdateView___________________________#
"""UpdateView is used to edit the fields of a pre-existing instance of a Model."""

class SchoolUpdateView(UpdateView):

    # Model that this view updates.
    model = models.School
    # Fields of the model that this view is allowed to update.
    fields = ('name', 'principal')
    

# DeleteView____________________________#
"""DeleteView requires a success_url attribute, that defines where to
redirect if delete operation is a success, here we redirect to school
list after a school is deleted. It also expects a confirmation page template
in local templates directory by the name 'modelname_confirm_delete.html'(all lowercase)"""
# A note on reverse_lazy() method
"""In Python, functions & methods are not executed on import; classes are. Therefore while using CBVs
one should use reverse_lazy() method while assigning success_url attribute outside a method,
or else the URLs will be resolved the moment the views file is imported to the urls file and
not when a call for that view(SchoolDeleteView) is made, if so the view will always return a
wrong URL. reverse_lazy() method resolves URL only when a call for that view is made and not
when the module is imported.
https://stackoverflow.com/questions/48669514/difference-between-reverse-and-reverse-lazy-in-django"""
class SchoolDeleteView(DeleteView):

    model = models.School
    success_url = reverse_lazy('basic_app:list')

Django/learning_cbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li class="nav-item"><a class="nav-link" href="#">#</a></li>
        </ul>
    </nav>
    {% block body_block %}
        
    {% endblock %}
</body>
</html>

Django/learning_cbv/basic_app/templates/basic_app/school_confirm_delete.html
<!-- A template displayed if a user is deleting a school manually -->
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
    <h1>Delete {{ school.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Delete" class="btn btn-danger">
        <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
    </form>
{% endblock %}

Django/learning_cbv/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1 class="h1">Welcome to schools detail page</h1>
        <h2>School details: </h2>

        <p>Name: {{ school_detail.name }}</p>
        <p>Principal: {{ school_detail.principal }}</p>
        <p>Location: {{ school_detail.location }}</p>
        <h3> Students: </h3>
        <!-- students is the related_name of foreign key in the student model-->
        <!-- This will return all the instances of students that have this school in their foreign key column. -->
        {% for student in school_detail.students.all %}
            <p>Name: {{student.name}}, age: {{student.age}} year old.</p>
        {% endfor %}
    </div>

    <!-- Update & delete Button -->
    <div class="container-fluid">
        <a href="{% url 'basic_app:student' %}"><button class='btn btn-info'>Add Student</button></a>

        <a href="{% url 'basic_app:update' pk=school_detail.pk %}"><button class="btn btn-warning ml-2">Update</button></a>

        <a href="{% url 'basic_app:delete' pk=school_detail.pk %}"><button class='btn btn-danger ml-2'>Delete</button></a>
    </div>
{% endblock %}

Django/learning_cbv/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
<!-- We can use the same form template for creating a School instance or
Updating it, therefore we check if an instance with that pk exists or not
if not then it is a new school, if so it is an old school being updated -->
    <h1>
        {% if not form.instance.id %}       <!-- if pk not in db -->
            Create School
        {% else %}                          <!-- if pk in db-->
            Update School
        {% endif %}
    </h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" class="btn btn-primary bg-success">
    </form>
{% endblock %}

Django/learning_cbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
    <div class="jumbotron">
        <h1 class="h1">Welcome to a list of all the Schools!</h1>

        <ol>
            {% for school in schools %}
                <!-- .id is the default primary-key if no primary-key is given to the Model -->
                <h2 class="h2"><li><a href="{{ school.id }}">{{ school.name }}</a></li></h2>
            {% endfor %}
        </ol>
    </div>

    <button class="btn btn-primary bg-success">
        <a href="{% url 'basic_app:create' %}" style="color: black;">Add</a>
    </button>
{% endblock %}

Django/learning_cbv/basic_app/templates/basic_app/student_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" class="btn btn-primary bg-success" value="Submit">
    </form>
{% endblock %}

Django/learning_cbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
              integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li class="nav-item"><a class="nav-link" href="#">#</a></li>
        </ul>
    </nav>

        {% block body_block %}
            
        {% endblock %}
</body>
</html>

Django/learning_cbv/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1 class="h1">Home Page</h1>
    </div>
{% endblock %}    