Django/learning_templates/basic_app/urls.py
from django.urls import path, include
from basic_app import views

# Global variable for finding app in template tagging.
# Django will look for the variable named 'app_name' in this module
app_name = 'basic_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

Django/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))
]

Django/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):

    context_dict = {'text': 'hello world', 'number': 100}
    return render(request, 'basic_app/index.html', context=context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

Django/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap 4.6 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Base Templates</title>
</head>
<body>
    <nav class="navbar bg-success navbar-light fixed-top">
        <div class="container">
            <ul class="nav">
                <li><a class="navbar-brand d-inline-block" href="{% url 'basic_app:index' %}">Brand</a></li>
                <li><a class="nav-link pr-2 text-dark d-inline-block" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="nav-link text-dark d-inline-block" href="{% url 'basic_app:other' %}">Other</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <!-- Creating a block named body_block.
        Refrence this body block in other HTML files that will inherit this base HTML
        and add the page specific code inside the block. -->
        {% block body_block %}

        <!-- Anything outside of this will be inherited. -->
        {% endblock %}

    </div>
</body>
</html>

Django/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
<!-- <html lang="en">
<head>
    <title>index page</title>
</head>
<body>
    <h1>Welcome to index page.</h1>
</body>
</html> -->

{% extends "basic_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to Index</h1>
        <h1>This is index.html page showing.</h1>

        <!-- using our custom filter on text and passing it a arg. -->
        <h1>{{ text|cut:'hello'}}</h1>
        <!-- using built-in filter 'add' and passing it arg 69-->
        <h1>{{ number|add:"69" }}</h1>
        
    {% endblock %}

Django/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
<!-- <html lang="en">
<head>
    <title>Other</title>
</head>
<body>
    <h1>Welcome to other page.</h1>
</body>
</html> -->

<!-- Using template inheritence. -->
<!-- this inherits the base HTML page. -->
{% extends "basic_app/base.html" %}

    {% block body_block %}
        <br><br><br>

        <h1>Welcome to other page</h1>
        <h2>This is an example of template inheritance!</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p><br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore blanditiis deleniti dignissimos voluptas et sint dolore veritatis cum, eligendi laboriosam explicabo est impedit recusandae a cumque aliquam perspiciatis incidunt perferendis!</p>

    {% endblock %}

Django/learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Relative</title>
    </head>
    <body>
        <h1>Welcome To relative URL templates</h1>
        <!-- basic_app is the global varible from urls.py & other is the name parameter of 'other/' pattern.-->
        <!-- Do not leave spaces! -->
        <a href="{% url 'basic_app:other' %}">The Other Page</a>
        <a href="{% url 'admin:index' %}">Admin</a>
        <a href="{% url 'index' %}">Index</a>
    </body>
</html>