Django/myblog/blog/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'blog'

urlpatterns = [
    #________________Post URLs_______________#
    
    re_path(r'^(?P<pk>[\d]+)$', views.PostDetailView.as_view(), name='post_detail'),                # post Detail view
    path('new/', views.CreatePostView.as_view(), name='post_new'),                                  # Post Create View
    re_path(r'^(?P<pk>[\d]+)/edit/$', views.PostUpdateView.as_view(), name='post_update'),          # Post Update View
    re_path(r'^(?P<pk>[\d]+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),        # Post Delete View
    re_path(r'^(?P<pk>[\d]+)/publish/$', views.post_publish, name='post_publish'),                  # Post Publish View
    #________________Comment URLs____________#
    re_path(r'^(?P<pk>[\d]+)/comment/$', views.add_comment_to_post, name='post_comment'),
    re_path(r'^comment/(?P<pk>[\d]+)/approve/$', views.comment_approve, name='comment_approve'),
    re_path(r'^comment/(?P<pk>[\d]+)/remove/$', views.comment_remove, name='comment_remove'),
]

Django/myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as au_views
from blog.views import (PostList, AboutView, DraftListView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', PostList.as_view(), name='post_list'),                                 # Home page
    path('post/', include('blog.urls', namespace='blog')),                          # App URLs redirect
    path('about/', AboutView.as_view(), name='about'),                              # About page
    path('drafts/', DraftListView.as_view(), name='post_draft_list'),               # Draft List
    #_________________Authorization views_________________#
    path('accounts/login/', au_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', au_views.LogoutView.as_view(), name='logout', kwargs={'next_page': ''}),
]

Django/myblog/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        # Here comments is the relation name o fforeign key in Comments class
        return self.comments.filter(approve_comment=True)

    def get_absolute_url(self):
        """Returns URL for the instance after creating it.
        you can call this method directly in Templates"""
        
        return reverse("blog:post_detail", kwargs = {'pk': self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    # post to which the comment belongs.
    post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField(max_length=2000)
    create_date = models.DateTimeField(default=timezone.now)
    approve_comment = models.BooleanField(default=False)

    def approve(self):
        self.approve_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('post_list')

    def __str__(self):
        return self.text

Django/myblog/blog/forms.py
from django import forms
from . import models

class PostForm(forms.ModelForm):

    class Meta():
        model = models.Post
        fields = ['author', 'title', 'text']

        # Settingup widgets for form
        widgets= {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontect'})
        }


class CommentForm(forms.ModelForm):

    class Meta():
        model = models.Comment
        fields = ['author', 'text']

        widgets = {
            'author': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'})
        }

Django/myblog/blog/views.py
from django.shortcuts import (render, get_object_or_404, redirect)
from django.views.generic import (TemplateView, ListView,
                                    DetailView, CreateView,
                                    UpdateView, DeleteView)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.urls import reverse_lazy

from . import models
from .forms import PostForm, CommentForm

# Create your views here.
class AboutView(TemplateView):
    template_name = 'blog/about.html'


class PostList(ListView):
    model = models.Post

    def get_queryset(self):
        # A queryset defines an SQL query
        # the statement below is equivalent to: SELECT * FROM Post WHERE published_date <= timezone.now()
        # __lte = less then or = to
        return models.Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    

class PostDetailView(DetailView):
    model = models.Post


class CreatePostView(LoginRequiredMixin, CreateView):
    """A view foor creating Posts.
    The view requires Login, therefore LoginRequiredMixin is used
    login_url: URL to redirect if user is not logged in.
    redirect_field_name: redirect path after login."""

    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'

    form_class = PostForm
    model = models.Post


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'

    form_class = PostForm
    model = models.Post
    template_name = 'blog/post_form.html'


class PostDeleteView(LoginRequiredMixin, DeleteView):
    
    model = models.Post
    success_url = reverse_lazy('blog:post_list')

    template_name = 'blog/post_confirm_delete.html'


class DraftListView(LoginRequiredMixin, ListView):
    """A View for rendering a list of unpublished blogs."""

    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'

    model = models.Post
    template_name = "blog/post_draft_list.html"

    context_object_name = 'posts'

    def get_queryset(self):
        """SELECT * FROM Post WHERE published_date IS NULL"""
        return models.Post.objects.filter(published_date__isnull=True).order_by('create_date')


@login_required
def post_publish(request, pk):
    """A view for publishing the posts in Draft."""

    post = get_object_or_404(models.Post, pk=pk)
    post.publish()
    print('published')
    return redirect('blog:post_detail', pk=pk)

#######################################################
#           Function Based views for Comments         #
#######################################################

@login_required
def add_comment_to_post(request, pk):   # pk will be passed by comment button.
    """A view for adding comment."""

    post = get_object_or_404(models.Post, pk=pk)        # gets the instance of passed Model with passed pk

    if request.method == 'POST':        # If a comment is submmited.
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post         # associating post field in comment to this post instance.
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:                               # comment page is requested.
        form = CommentForm()
    
    return render(request, 'blog/comment_form.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(models.Comment, pk=pk)
    comment.approve()

    return redirect('blog:post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(models.Comment, pk=pk)
    post_pk = comment.post.pk 
    comment.delete()
    return redirect('blog:post_detail', pk=post_pk)

Django/myblog/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <br><br><br><br><br>
    <h1>About this company</h1>
    <p>Thanks for checking it out!</p>
{% endblock %}

Django/myblog/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!-- Medium style Editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'CSS/blog.css' %}">
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Russo+One&display=swap" rel="stylesheet"> 

</head>
<body>
    <!-- NavBar -->
        <nav class='navbar navbar-expand-md navabr-light bg-light fixed-top techfont'>
            <div class="navbar-header">
                <li class="nav-item"><a class="navbar-brand bigbrand" href="{% url 'post_list' %}">My blog</a></li>
            </div>

            <div class='container'>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a href="{% url 'blog:post_new' %}">New Post</a></li>
                        <li class="nav-item ml-4"><a href="{% url 'post_draft_list' %}">Drafts</a></li>
                        <li class="nav-item ml-4"><a href="{% url 'logout' %}">Log Out</a></li>
                        <li class="nav-item ml-4"> <a href="#"> Welcome: {{ user.username }}</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav navbar-right" href="{% url 'login' %}">Login</a></li>
                    {% endif %}
                </ul>

                <ul class="nav navbar-nav navbar-left">
                    <li class="nav-item"><a href="{% url 'about' %}">About</a></li>
                    <li class="nav-item ml-4"><a href="https://www.github.com">Github</a></li>
                    <li class="nav-item ml-4"><a href="https://www.linkedin.com">LinkedIn</a></li>
                </ul>
            </div>
        </nav>
    <!-- Content Block -->
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                <div class="blog_posts">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Django/myblog/blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}
{% block content %}
<br><br><br><br>

    <h1>New Comment</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-primary">Post Comment</button>
    </form>

    <script>
        var editor = new MediumEditor('.editable');
    </script>
{% endblock %}

Django/myblog/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
<br><br><br><br>

    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object }}</p>

        <input type="submit" class="btn btn-danger" value="Confirm">
    </form>
{% endblock %}

Django/myblog/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
<br><br><br><br>

<h1 class="posttitle loader">{{ post.title }}</h1>
{% if post.published_date %}            <!--If post is published-->
    <div class="date postdate">
        {{ post.published_date }}
    </div>
{% else %}
    <a  class="btn btn-primary" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
{% endif %}
    <p class='postcontent'>{{ post.text|safe|linebreaksbr }}</p>

{% if user.is_authenticated %}
    <!-- Edit Button -->
    <a class="btn btn-primary" href="{% url 'blog:post_update' pk=post.pk %}">
        <span>Edit</span>
    </a>
    <!-- Delete Button -->
    <a class="btn btn-primary" href="{% url 'blog:post_remove' pk=post.pk %}">
        <span>Delete</span>
    </a>
{% endif %}

    <hr>
    <a class='btn btn-primary' href="{% url 'blog:post_comment' pk=post.pk %}">Comment</a>

    <!-- Comments list -->
    <div class='container'>
        {% for comment in post.comments.all %}
            <br>
            {% if user.is_authenticated or comment.approve_comment %}  <!-- If comment is approved -->
                {{ comment.create_date }}
                    {% if not comment.approve_comment %}               <!-- If comment is not approved -->
                        <!-- delete comment -->
                        <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}">
                            <span class="glyphicon glyphicon-remove">Remove</span>
                        </a>
                        <!-- Approve comment -->
                        <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}">
                            <span class="glyphicon glyphicon-ok">Approve</span>
                        </a>                
                    {% endif %}

                    <p>{{ comment.text|safe|linebreaks }}</p>
                    <p>Posted By: {{ comment.author }}</p>
                    
                    <hr>
            {% endif %}

            {% empty %}     <!-- If no comments found -->
            <p>No Comments!</p>

        {% endfor %}
    </div>

{% endblock %}

Django/myblog/blog/templates/blog/post_draft_list.html
{% extends "blog/base.html" %}
{% block content %}
    <br><br><br><br>
    <h1>This is draft page</h1>
    <hr><br>
    
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.create_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <!-- truncatechars filter will truncate after 200 charecters -->
            <p>{{ post.text|safe|truncatechars:200 }}</p>
        </div>
        <hr>
    {% endfor %}
{% endblock %}

Django/myblog/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% block content %}
    <br><br><br><br><br>
    {% if post.title %}
        <h1>{{ post.title }}</h1>
    {% else %}
        <h1>New Post</h1>
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="save btn btn-primary">Save</button>
    </form>

    <!-- Adding Medium editor -->
    <script>
        var editor = new MediumEditor('.editable');
    </script>
{% endblock %}

Django/myblog/blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}
<br><br><br><br>
    <H3>This is List page</H3>
    <hr><br>

    <div class="centerstage">
        {% for post in post_list %}
            <div class="post">
                <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
                <div class='date'>
                    <p>Published on: {{ post.published_date|date:'D M Y' }}</p>
                </div>
                <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
            </div>
            <hr>
        {% endfor %}
    </div>
{% endblock %}